name: tianchi-purchase-redemption
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - jupyterlab
  - notebook
  - numpy=1.23.5
  - pandas
  - matplotlib
  - scikit-learn
  - pip:
      - tensorflow==2.10.1
